config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  root 'posts#index'
  resources :posts do
    resources :comments
    resources :upvotes, only: :create
    resources :downvotes, only: :create
  end
  resources :users, only: :show
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user

  validates :text, :user_id, :post_id, presence: true
  delegate :name, to: :user, prefix: true
end

app/models/post.rb
# frozen_string_literal: true

class Post < ActiveRecord::Base
  mount_uploader :photo, PhotoUploader
  belongs_to :user
  has_many :comments, dependent: :destroy

  validates :photo, :description, :user_id, presence: true
  acts_as_votable

  delegate :photo, :name, to: :user, prefix: true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  mount_uploader :photo, PhotoUploader
  has_many :posts
  has_many :comments
  has_many :active_relationships, class_name: 'Relationship', foreign_key: 'follower_id', dependent: :destroy
  acts_as_voter
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |u|
      u.permit(:email,
               :password,
               :password_confirmation,
               :name,
               :photo)
    end
    devise_parameter_sanitizer.permit(:sign_in) do |u|
      u.permit(:email,
               :password,
               :remember_me)
    end
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:email,
               :password,
               :password_confirmation,
               :current_password,
               :name,
               :photo)
    end
  end
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ApplicationController
  before_action :authenticate_user!, only: :create
  before_action :owner?, only: :destroy
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params.merge(user_id: current_user.id))
    if @comment.valid?
    else
      flash[:alert] = 'Invalid attributes.'
    end
    redirect_to root_path
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to root_path
  end

  private

  def owner?
    @comment = Comment.find(params[:id])
    redirect_to root_path if @comment.user != current_user
  end

  def comment_params
    params.require(:comment).permit(:text, :post_id)
  end
end

app/controllers/downvotes_controller.rb
# frozen_string_literal: true

class DownvotesController < ApplicationController
  before_action :authenticate_user!
  def create
    @post = Post.find(params[:post_id])
    @post.downvote_from current_user

    respond_to do |format|
      format.html { redirect_to posts_path }
      format.js {}
    end
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :authenticate_user!, only: %i[new create]
  before_action :owner?, only: %i[edit update]
  before_action :owner?, only: %i[edit update destroy]
  def index
    @posts = Post.all.order('created_at DESC')
                 .includes(:user, comments: :user)
                 .paginate(page: params[:page], per_page: 3)
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.create(post_params)
    if @post.valid?
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @post.update(post_params)
    if @post.valid?
      redirect_to root_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.delete
    redirect_to root_path
  end

  private

  def owner?
    redirect_to root_path if Post.find(params[:id]).user != current_user
  end

  def post_params
    params.require(:post).permit(:user_id, :photo, :description)
  end
end

app/controllers/upvotes_controller.rb
# frozen_string_literal: true

class UpvotesController < ApplicationController
  before_action :authenticate_user!
  def create
    @post = Post.find(params[:post_id])
    @post.liked_by current_user

    respond_to do |format|
      format.html { redirect_to posts_path }
      format.js {}
    end
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/comments_helper.rb
# frozen_string_literal: true

module CommentsHelper
end

app/helpers/downvotes_helper.rb
# frozen_string_literal: true

module DownvotesHelper
end

app/helpers/followers_helper.rb
# frozen_string_literal: true

module FollowersHelper
end

app/helpers/followings_helper.rb
# frozen_string_literal: true

module FollowingsHelper
end

app/helpers/follows_helper.rb
# frozen_string_literal: true

module FollowsHelper
end

app/helpers/posts_helper.rb
# frozen_string_literal: true

module PostsHelper
end

app/helpers/upvotes_helper.rb
# frozen_string_literal: true

module UpvotesHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/downvotes/create.js.erb
$('#likes_container_<%= @post.id %>').html("<%= escape_javascript render partial: '/posts/likes', locals: { post: @post } %>")

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Share Your Photos Online-Photopost</title>
    <%= favicon_link_tag 'favicon.ico' %>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <link href='https://fonts.googleapis.com/css?family=Satisfy|Kushan+Script' rel='stylesheet' type='text/css'>
  </head>

<body>
  
<nav>
  <div class="container-fluid">
    <div class="row">
      <div class = "col-lg-6 col-lg-offset-3">
        <div class="row">
          <div class="nav_wrapper">
            <div class="col-xs-4">
              <span class="pull-right brand"><i class="fa fa-instagram" aria-hidden="true"></i> | <%= link_to 'Photopost', root_path %></span>
            </div>
            <div class="col-xs-8">
    	       <% if user_signed_in? %>
              <span class="nav_links pull-right"><%= link_to '', new_post_path, class: 'glyphicon glyphicon-edit fa-2x' %></span>
              <span class="nav_links pull-right"><%= link_to '', edit_user_registration_path, class: 'glyphicon glyphicon-cog fa-2x'%></span>
              <span class="nav_links pull-right"><%= link_to '', destroy_user_session_path, class: 'glyphicon glyphicon-log-out fa-2x'%></span>
              <% else %>
              <span class="nav_links pull-right"><%= link_to 'Sign up', new_user_registration_path %></span>
              <span class="nav_links pull-right"><%= link_to 'Log in', new_user_session_path %></span>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

</nav>  
    <div class = "container-fluid">
        <%= yield %>
    </div>
</body>
</html>

app/views/posts/_likes.html.erb
<% if user_signed_in? %>
  <span class="post_like">
    <% if current_user.voted_up_on? post %>
      <%= link_to '<i class="fa fa-heart" aria-hidden="true"></i>'.html_safe, post_downvotes_path(post.id), method: :post,remote: true %> 
    <% else %>
      <%= link_to '<i class="fa fa-heart-o" aria-hidden="true"></i>'.html_safe, post_upvotes_path(post.id), method: :post, remote: true %>
    <% end %>

    <%= pluralize post.get_likes.size, "like" %>
  </span>
<% else %>
  <span class="post_like">
    <i class="fa fa-heart-o" aria-hidden="true"></i> <%= pluralize post.get_likes.size, "like" %>
  </span>
<% end %>

app/views/posts/_post.html.erb
<div class ="row">
  <div class = "col-md-6 col-md-offset-3">
      <div class ="post_box">
       <div class = "post_header">
         <%= image_tag post.user_photo, class: 'prof_pic_small' %>
         <%= link_to post.user_name, user_path(post.user_id) %>
         <span class="timestamp pull-right"><%= distance_of_time_in_words(DateTime.now, post.created_at) %> ago</span>
         <hr>
        </div>

        <%= image_tag post.photo, class: 'photo' %>
    
        <div class="post_body">
          <%= link_to post.user_name, user_path(post.user_id), class: 'name' %> <%= post.description %>
          <% if post.user == current_user %>
          <div class = "pull-right"><%= link_to '', edit_post_path(post.id),class: 'fa fa-pencil' %>
           <%= link_to '', post_path(post.id), method: :delete, class: 'fa fa-trash' %></div>
          <% end %>
        </div>
<hr>
        <div class="post_comments">
          <% post.comments.each do |comment| %><br />
            <%= link_to comment.user_name,  user_path(comment.user_id), class: 'name' %>
            <%= comment.text %>
            <% if comment.user == current_user %>
            <%= link_to '', post_comment_path(post_id: post.id, id: comment.id),class: 'pull-right fa fa-remove', method: :delete%>
            <% end %>
          <% end %>
        <hr>

        <span id="likes_container_<%= post.id %>">
            <%= render partial: 'likes', locals: {post: post} %>
        </span>


             <% if user_signed_in? %>
               <%= simple_form_for Comment.new, url: post_comments_path(post), method: :post,html: {class:'form-horizontal'} do |f| %>
               <%= f.input :text, label: 'Comment', placeholder: 'Add a comment' %>
               <%= f.submit 'Post', class: 'btn btn-primary', data: {disable_with: "Posting..."} %>
              <% end %>
            <% end %>
        </div>
      </div>
    
  </div>
</div>

app/views/posts/edit.html.erb
<div class = "col-md-4"></div>
	<div class = "col-md-4">
		<div class = "panel-body">
			<div class = "post_box newpost">
				<h4 class = "brand text-center">Edit Post</h4>
					<%= simple_form_for @post do |f| %>
					<%= f.input :photo %>
					<%= f.input :description %>
					<%= f.submit 'Update', class:'btn btn-success', data: { disable_with: "Updating..." } %>
				<% end %>
			</div>
		</div>
	</div>
</div>
<div class = "col-md-4">
</div>

app/views/posts/index.html.erb
<div id = "posts">
  <% @posts.each do |post| %>
  <%= render partial: 'post',locals: {post:post} %>
  <% end %>
</div>
<%= will_paginate @posts %>

app/views/posts/index.js.erb
$('#posts').append('<%= escape_javascript render(@posts) %>');
$('.pagination').replaceWith('<%= escape_javascript will_paginate(@posts) %>');

app/views/posts/new.html.erb
<div class = "col-md-4"></div>
	<div class = "col-md-4">
		<div class = "panel-body">
			<div class = "post_box newpost">
				<h4 class = "brand text-center">New Post</h4>
					<%= simple_form_for @post do |f| %>
					<%= f.input :photo %>
					<%= f.input :description %>
					<%= f.submit 'Post', class:'btn btn-success', data: { disable_with: "Posting..." } %>
				<% end %>
			</div>
		</div>
	</div>
</div>
<div class = "col-md-4">
</div>

app/views/posts/show.html.erb
<%= image_tag @post.user.photo %>
<%= @post.user.name %>
<%= image_tag @post.photo %>
<%= @post.description %>
<% if @post.user_id == current_user.id %>
  <%= link_to 'Edit Post', edit_post_path(@post.id) %>
  <%= link_to 'Delete Post', post_path(@post.id), method: :delete %>
<% end %>

app/views/upvotes/create.js.erb
$('#likes_container_<%= @post.id %>').html("<%= escape_javascript render partial: '/posts/likes', locals: { post: @post } %>")

app/views/users/show.html.erb
<div class = "pp">
<div class="prof_header">
	<div class = "row">
		
		<div class = "col-xs-4">
<%= image_tag @user.photo, class: 'prof_pic'%></div>

<div class= "col-xs-8">
	<div class = "user_header">
		<div class= "row">

<div class="username"><%= @user.name %>
	</div><hr>
<div class = "col-xs-2">
<span class = "count">
<%= pluralize(@user.posts.count, 'post')%>
</span>
</div>

<div class= "col-xs-6">
	<%= link_to 'Edit Profile',edit_user_registration_path(@user), class: 'user_edit_button btn btn-danger' if user_signed_in? && @user == current_user %>
	</div>
	
</div>
</div>
</div>


</div>
<hr>
</div>

<div class = "prof_post_box">
	<div class = "row">
		<div class = "col-xs-3"></div>
		<div class ="col-xs-6 myprof">
        <% @user.posts.each do |post| %>
        <%= image_tag post.photo_url,class: 'prof_show' %>



<% end %>
</div>
<div class = "col-xs-3"></div>

</div>
</div>
</div>